name: Push to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**' # GitHub Actions changes
      - 'Dockerfile'           # Dockerfile changes
      - 'go.*'                 # go.mod or go.sum changes
      - 'cmd/**'               # command changes
      - 'internal/**'          # internal package changes

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  deploy:
    name: Build and push
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "registry.digitalocean.com/stats-go/updater:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
