name: Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - 'go.*'                 # go.mod or go.sum changes
      - 'cmd/**'               # command changes
      - 'internal/**'          # internal package changes

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
